version: '3.8'
services:
  n8n:
   
    image: docker.n8n.io/n8nio/n8n:1.83.2
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data-belis-n8n-f8fb9m:/home/node/.n8n
    networks:
      - belis-n8n-f8fb9m
    labels:
      - traefik.http.routers.belis-n8n-f8fb9m-2-web.rule=Host(`belis-n8n-5f9361-31-97-53-209.traefik.me`)
      - traefik.http.routers.belis-n8n-f8fb9m-2-web.entrypoints=web
      - traefik.http.services.belis-n8n-f8fb9m-2-web.loadbalancer.server.port=5678
      - traefik.http.routers.belis-n8n-f8fb9m-2-web.service=belis-n8n-f8fb9m-2-web
      - traefik.enable=true
volumes:
  n8n_data-belis-n8n-f8fb9m: null
networks:
  belis-n8n-f8fb9m:
    name: belis-n8n-f8fb9m
    external: true